name: Deploy firebase hosting
description: "Deploy firebase hosting"
inputs:
  firebase-project-id:
    description: Project id
    required: true
  working-directory:
    description: Directory for npm ci and deploy artifacts
    required: false
    default: .
  build-directory:
    description: Directory for build artifacts
    required: false
    default: dist
runs:
  using: composite
  steps:
    - uses: Albertbol/workflows/.github/actions/node-setup@main
    - shell: bash
      run: |
        npm ci
        npm run build
      working-directory: ${{ inputs.working-directory }}
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --project ${{ inputs.firebase-project-id }}
