name: Deploy firebase security rules
description: "Deploy firebase security rules"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only firestore:rules
      env:
        GCP_SA_KEY: env.GCP_SA_KEY
