name: Push Supabase migrations
description: Push Supabase migrations

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - shell: bash
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push