name: Supabase types diff check for typescript
description: Supabase types diff check for typescript
inputs:
  supabase-gen-types-directory:
    description: Directory for generated types
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - shell: bash
        run: |
          supabase db start
          npm run gen-supabase-local-types
          if ! git diff --ignore-space-at-eol --exit-code --quiet ${{ inputs.supabase-gen-types-directory }}; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi