name: Supabase types diff check for typescript
description: Supabase types diff check for typescript
inputs:
  supabase-gen-types-directory:
    description: Directory for generated types
    required: true

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - shell: bash
        env:
          SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID: test
          SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET: test
          SUPABASE_AUTH_EXTERNAL_APPLE_CLIENT_ID: test
          SUPABASE_AUTH_EXTERNAL_APPLE_SECRET: test
        run: |
          if grep -q 'signing_keys_path' supabase/config.toml && [ ! -f supabase/signing_keys.json ]; then
            supabase gen signing-key --algorithm ES256
          fi
          supabase db start
          npm run gen-supabase-local-types
          if ! git diff --ignore-space-at-eol --exit-code --quiet ${{ inputs.supabase-gen-types-directory }}; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi