name: Supabase reset and seeding
description: Supabase reset and seeding

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: supabase/setup-cli@v1
      with:
        version: latest
    - uses: Albertbol/workflows/.github/actions/node-setup@main
    - shell: bash
      run: |
        cd functions
        npm ci
        cd ..
        npm ci
        supabase link --project-ref $SUPABASE_PROJECT_ID
        supabase db start
        npm run db-reset
