name: Supabase reset and seeding
description: Supabase reset and seeding

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: supabase/setup-cli@v1
      with:
        version: latest
    - uses: Albertbol/workflows/.github/actions/node-setup@main
    - shell: bash
      run: |
        cd functions
        npm ci
        cd ..
        npm ci
        supabase link --project-ref $SUPABASE_PROJECT_ID
        # Use a here document to provide the "y" input
        supabase db reset --linked <<EOF
        y
        EOF
