name: Trigger Codemagic pipeline
description: Trigger Codemagic pipeline
inputs:
  app_id:
    description: Codemagic application ID
    required: true
  workflow_id:
    description: Codemagic workflow ID
    required: true
  token:
    description: Codemagic API token
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger Codemagic build
      uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
      with:
        app-id: ${{ inputs.app_id }}
        workflow-id: ${{ inputs.workflow_id }}
        token: ${{ inputs.token }}
