name: Analyze
description: Dart Code Metrics
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: dart-code-metrics
      uses: dart-code-checker/dart-code-metrics-action@v3
