name: Analyze
description: Flutter Analyze
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: "zulu"
        java-version: "11"
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - shell: bash
      run: |
        flutter pub get
        flutter --version
        flutter pub run dart_code_metrics:metrics analyze lib
        flutter pub run dart_code_metrics:metrics check-unused-code lib
        flutter pub run dart_code_metrics:metrics check-unused-files lib
