name: Lint
description: Lint
inputs:
  working-directory:
    description: Directory for npm ci and npm run lint
    required: false
    default: .
runs:
  using: "composite"
  steps:
    - uses: Albertbol/workflows/.github/actions/node-setup@main
    - shell: bash
      run: |
        npm ci
        npm run lint
      working-directory: ${{ working-directory }}
