name: Setup node
description: "Setup node"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v2
      with:
        node-version: 20
        cache-dependency-path: "**/package-lock.json"
        cache: "npm"
