name: Cloudflare Workers Deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Deployment environment'
        required: true
      workingDirectory:
        type: string
        description: 'Working directory for the project'
        required: true
      monorepo-directory:
        type: string
        description: 'Monorepo directory'
        required: false
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ACCOUNT_ID:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: Albertbol/workflows/.github/actions/node-setup@main
      - shell: bash
        run: |
          npm ci
          npm run build
        working-directory: ${{ inputs.monorepo-directory }}
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: ${{ inputs.environment }}
          workingDirectory: ${{ inputs.workingDirectory }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.111.0"