name: Firebase qa work flow
on:
  workflow_call:
    secrets:
      GCP_SA_KEY:
        required: true
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/lint@main
        with:
          working-directory: functions
  build:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/build@main
        with:
          working-directory: functions
  test:
    needs: build
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/firebase-actions/test@main
        with:
          working-directory: functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
