name: Firebase work flow
on:
  workflow_call:
jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/node-setup@main
      - run: npm ci
        working-directory: functions
  qa:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/lint@main
        with:
          working-directory: functions
  build:
    needs: qa
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/build@main
        with:
          working-directory: functions
  test:
    needs: build
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/build@main
        with:
          working-directory: functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
