name: Firebase deploy work flow
on:
  workflow_call:
    inputs:
      firebase-project-id:
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        required: true
jobs:
  deploy-security-rules:
    name: Deploy security rules
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/firebase/rules@main
        with:
          firebase-project-id: ${{ inputs.firebase-project-id }}
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  deploy-cloud-functions:
    name: Deploy cloud functions
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/firebase/functions@main
        with:
          working-directory: functions
          firebase-project-id: ${{ inputs.firebase-project-id }}
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  deploy-hosting:
    name: Deploy hosting
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/firebase/hosting@main
        with:
          working-directory: functions
          firebase-project-id: ${{ inputs.firebase-project-id }}
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
