name: Firebase deploy work flow
on:
  workflow_call:
    secrets:
      GCP_SA_KEY:
        required: true
jobs:
  deploy-security-rules:
    name: Deploy security rules
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/firebase/rules@main
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  deploy-cloud-functions:
    name: Deploy cloud functions
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/firebase/functions@main
        with:
          working-directory: functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  deploy-hosting:
    name: Deploy hosting
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/firebase/hosting@main
        with:
          working-directory: functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
