name: Firebase deploy work flow
on:
  workflow_call:
    secrets:
      GCP_SA_KEY:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/build@main
        with:
          working-directory: functions
  deploy-security-rules:
    name: Deploy security rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  deploy-cloud-functions:
    name: Deploy cloud functions
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
