name: Flutter qa work flow
on:
  workflow_call:
    secrets:
      PTA_TOKEN:
        required: true
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/test/flutter@main
    env:
      GITHUB_TOKEN: ${{ secrets.PTA_TOKEN }}
