name: Flutter qa work flow
on:
  workflow_call:
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_KEY }}
      - uses: Albertbol/workflows/.github/actions/test/flutter@main
        with:
          token: ${{ steps.app-token.outputs.token }}
