name: Flutter qa work flow
on:
  workflow_call:
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      - uses: Albertbol/workflows/.github/actions/test/flutter@main
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
