name: Firebase deploy work flow
on:
  workflow_call:
    secrets:
      GCP_SA_KEY:
        required: true
      SUPABASE_ACCESS_TOKEN:
        required: true
      SUPABASE_DB_PASSWORD:
        required: true
      SUPABASE_PROJECT_ID:
        required: true
jobs:
  push-migrations:
    name: Push migrations
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/supabase/migrations@main
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
  deploy-security-rules:
    name: Deploy security rules
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/firebase/rules@main
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  deploy-cloud-functions:
    name: Deploy cloud functions
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/firebase/functions@main
        with:
          working-directory: functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  deploy-hosting:
    name: Deploy hosting
    runs-on: ubuntu-latest
    steps:
      - uses: Albertbol/workflows/.github/actions/deploy/firebase/hosting@main
        with:
          working-directory: functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
